sudo: required
services:
  - docker

before_install:
  - docker build -t bmcghee1101/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true bmcghee1101/react-test npm test 

after_success:
  - docker build -t bmcghee1101/multi-client ./client
  - docker build -t bmcghee1101/multi-nginx ./nginx
  - docker build -t bmcghee1101/multi-server ./server
  - docker build -t bmcghee1101/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bmcghee1101/multi-client
  - docker push bmcghee1101/multi-nginx
  - docker push bmcghee1101/multi-server
  - docker push bmcghee1101/multi-worker